from datetime import datetime
from io import BytesIO
import textwrap


PAGE_WIDTH = 612
PAGE_HEIGHT = 792
MARGIN = 54
CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2)
LINE_HEIGHT = 14


def generate_session_pdf_report(session_details: dict) -> bytes:
    """Generate a comprehensive multi-question interview report PDF."""
    pdf = _PDFDocument()
    y = _new_page(pdf)
    
    role = session_details.get("role") or "None"
    mode = session_details.get("mode", "Technical")
    tech_subj = session_details.get("technical_subject") or "None"
    overall = session_details.get("overall_score", 0.0)
    readiness = session_details.get("readiness_score", 0.0)
    level = session_details.get("readiness_level", "Developing")
    date_str = session_details.get("created_at", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

    title_desc = f"Interview Report: {mode}"
    if tech_subj != "None":
        title_desc += f" - {tech_subj}"
    if role != "None":
        title_desc += f" ({role})"

    y = _add_title(pdf, y, title_desc)
    y = _add_text(pdf, y, f"Mode: {mode}  |  Subject: {tech_subj}  |  Role: {role}  |  Date: {date_str}", size=10)
    y = _add_text(pdf, y, f"Overall Score: {overall:.1f}/100  |  Readiness Score: {readiness:.1f}/100 ({level})", size=10)
    y -= 14

    # Summary Metrics
    res = session_details.get("result") or {}
    metrics_items = [
        ("Technical Score", f"{res.get('technical_avg', 0.0):.1f}/10"),
        ("Communication", f"{res.get('communication_avg', 0.0):.1f}/10"),
        ("Problem Solving", f"{res.get('problem_solving_avg', 0.0):.1f}/10"),
        ("Delivery Confidence", f"{res.get('confidence_avg', 0.0):.1f}/10"),
        ("Questions Answered", str(len(session_details.get('questions', [])))),
        ("Readiness Level", level),
    ]
    y = _add_section_header(pdf, y, "Session Performance Summary")
    y = _add_metrics(pdf, y, metrics_items)
    y -= 8

    # Strengths & Weaknesses
    strengths = res.get("strengths") or []
    if strengths:
        if y < 120: y = _new_page(pdf)
        y = _add_section_header(pdf, y, "Key Strengths")
        y = _add_list(pdf, y, strengths[:4])
        y -= 8

    weaknesses = res.get("weaknesses") or []
    if weaknesses:
        if y < 120: y = _new_page(pdf)
        y = _add_section_header(pdf, y, "Areas for Improvement")
        y = _add_list(pdf, y, weaknesses[:4])
        y -= 8

    # Question Breakdown
    questions = session_details.get("questions") or []
    if questions:
        if y < 140: y = _new_page(pdf)
        y = _add_section_header(pdf, y, "Question Breakdown & Evaluations")
        for q in questions:
            if y < 140: y = _new_page(pdf)
            q_type_str = "Follow-up" if q.get("type") == "follow_up" else "Main"
            q_title = f"Q{q.get('order', 1)} [{q_type_str}]: {q.get('text', '')}"
            y = _add_paragraph(pdf, y, q_title)

            # Candidate answer summary if available
            ans_transcript = q.get("transcript")
            if ans_transcript:
                y = _add_text(pdf, y, f"Spoken Answer ({q.get('duration', 0.0):.1f}s, {q.get('words_per_minute', 0.0):.0f} WPM): {ans_transcript[:180]}...", size=9)

            ev = q.get("evaluation") or {}
            q_eval = f"Score: {ev.get('overall_score', 0):.0f}/100 (Tech: {ev.get('technical_score', 0)}/10, Comm: {ev.get('communication_score', 0)}/10) - {ev.get('feedback', 'No feedback recorded.')}"
            y = _add_paragraph(pdf, y, q_eval)
            y -= 6

    return pdf.render()


def generate_interview_report(data):
    report = _build_report_content(data or {})
    pdf = _PDFDocument()

    y = _new_page(pdf)
    y = _add_title(pdf, y, "AI Interview Coach Report")
    y = _add_text(pdf, y, "Generated by AI Interview Coach", size=10)
    y = _add_text(pdf, y, f"Date & Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", size=10)
    y -= 12

    for section in report:
        if y < 120:
            y = _new_page(pdf)

        y = _add_section_header(pdf, y, section["title"])
        if section["kind"] == "metrics":
            y = _add_metrics(pdf, y, section["items"])
        elif section["kind"] == "list":
            y = _add_list(pdf, y, section["items"])
        else:
            y = _add_paragraph(pdf, y, section["text"])
        y -= 8

    return pdf.render()


def _build_report_content(data):
    evaluation = data.get("ai_evaluation") or {}
    video = data.get("video_analysis") or {}
    feedback_text = (
        data.get("feedback")
        or evaluation.get("feedback")
        or evaluation.get("summary")
    )
    strengths_items = evaluation.get("strengths") or data.get("strengths") or []
    improvements_items = (
        evaluation.get("improvements")
        or evaluation.get("areas_for_improvement")
        or evaluation.get("weaknesses")
        or []
    )

    sections = [
        {
            "title": "Interview Question",
            "kind": "text",
            "text": _value(data.get("question")),
        },
    ]

    meta_parts = []
    if data.get("category"):
        meta_parts.append(f"Category: {data.get('category')}")
    if data.get("difficulty"):
        meta_parts.append(f"Difficulty: {data.get('difficulty')}")
    if data.get("traceability"):
        meta_parts.append(f"Traceability: {data.get('traceability')}")
    if meta_parts:
        sections.append({
            "title": "Question Context",
            "kind": "list",
            "items": meta_parts,
        })

    sections.extend([
        {
            "title": "Candidate Transcript",
            "kind": "text",
            "text": _value(data.get("transcript")),
        },
        {
            "title": "Overall Feedback",
            "kind": "text",
            "text": _value(feedback_text),
        },
        {
            "title": "Scores",
            "kind": "metrics",
            "items": [
                ("Overall Score", data.get("score")),
                ("Technical Score", evaluation.get("technical_score")),
                ("Communication Score", evaluation.get("communication_score")),
                ("Confidence Score", evaluation.get("confidence_score")),
                ("Leadership Score", evaluation.get("leadership_score")),
                ("Problem Solving Score", evaluation.get("problem_solving_score")),
            ],
        },
        {
            "title": "Video Metrics",
            "kind": "metrics",
            "items": [
                ("Face Visible Percentage", _percent(video.get("face_visible_percent"))),
                ("Eye Contact Score", video.get("eye_contact_score")),
                ("Head Stability Score", video.get("head_stability_score")),
                ("Visual Confidence Score", video.get("visual_confidence_score")),
                ("Look Away Count", video.get("look_away_count")),
                ("Total Look Away Duration", f"{video.get('total_look_away_duration', 0)}s" if video.get("total_look_away_duration") is not None else None),
            ],
        },
        {
            "title": "Look-Away Events",
            "kind": "list",
            "items": _format_look_away_events(video.get("look_away_events")),
        },
        {
            "title": "Strengths",
            "kind": "list",
            "items": _list_values(strengths_items),
        },
        {
            "title": "Areas for Improvement",
            "kind": "list",
            "items": _list_values(improvements_items),
        },
        {
            "title": "Ideal Answer",
            "kind": "text",
            "text": _value(data.get("ideal_answer")),
        },
        {
            "title": "Missing Points",
            "kind": "list",
            "items": _list_values(data.get("missing_points")),
        },
        {
            "title": "Improvement Suggestions",
            "kind": "list",
            "items": _list_values(data.get("improvement_suggestions")),
        },
    ])
    return sections


def _value(value):
    if value is None or value == "":
        return "Data not available"
    return str(value)


def _percent(value):
    if value is None or value == "":
        return None
    return f"{value}%"


def _format_look_away_events(events):
    if not isinstance(events, list) or not events:
        return ["No significant look-away events detected. Maintained steady camera-facing focus."]
    formatted = []
    for ev in events:
        num = ev.get("event_num", len(formatted) + 1)
        start = ev.get("start_time", "00:00")
        end = ev.get("end_time", "00:00")
        dur = ev.get("duration", 0)
        direction = ev.get("direction", "Away")
        formatted.append(f"Event {num}: {start} - {end} (Duration: {dur}s, Direction: {direction})")
    return formatted


def _list_values(items):
    if not isinstance(items, list) or not items:
        return ["Data not available"]

    values = []
    for item in items:
        if isinstance(item, dict):
            title = item.get("title") or item.get("label") or ""
            description = item.get("description") or item.get("text") or ""
            text = " - ".join(part for part in [title, description] if part)
            values.append(text or "Data not available")
        else:
            values.append(_value(item))
    return values


def _new_page(pdf):
    pdf.add_page()
    pdf.rect(0, PAGE_HEIGHT - 44, PAGE_WIDTH, 44, fill=(26, 54, 93))
    pdf.text(MARGIN, PAGE_HEIGHT - 28, "AI Interview Coach", size=14, color=(255, 255, 255), bold=True)
    return PAGE_HEIGHT - 72


def _add_title(pdf, y, text):
    pdf.text(MARGIN, y, text, size=20, color=(26, 54, 93), bold=True)
    return y - 28


def _add_section_header(pdf, y, text):
    pdf.rect(MARGIN, y - 18, CONTENT_WIDTH, 24, fill=(236, 241, 248))
    pdf.text(MARGIN + 10, y - 10, text, size=12, color=(26, 54, 93), bold=True)
    return y - 34


def _add_text(pdf, y, text, size=10):
    for line in _wrap(text, size=size):
        if y < 70:
            y = _new_page(pdf)
        pdf.text(MARGIN, y, line, size=size, color=(55, 65, 81))
        y -= LINE_HEIGHT
    return y


def _add_paragraph(pdf, y, text):
    return _add_text(pdf, y, _value(text), size=10)


def _add_list(pdf, y, items):
    for item in items:
        for index, line in enumerate(_wrap(item, width=88)):
            if y < 70:
                y = _new_page(pdf)
            prefix = "- " if index == 0 else "  "
            pdf.text(MARGIN + 8, y, prefix + line, size=10, color=(55, 65, 81))
            y -= LINE_HEIGHT
    return y


def _add_metrics(pdf, y, items):
    label_x = MARGIN + 10
    value_x = MARGIN + 260
    for label, value in items:
        if y < 70:
            y = _new_page(pdf)
        pdf.text(label_x, y, label, size=10, color=(55, 65, 81), bold=True)
        pdf.text(value_x, y, _value(value), size=10, color=(17, 24, 39))
        y -= LINE_HEIGHT + 2
    return y


def _wrap(text, width=96, size=10):
    text = _value(text).replace("\r", "\n")
    lines = []
    for paragraph in text.split("\n"):
        if not paragraph.strip():
            lines.append("")
            continue
        lines.extend(textwrap.wrap(paragraph, width=width))
    return lines or ["Data not available"]


class _PDFDocument:
    def __init__(self):
        self.pages = []

    def add_page(self):
        self.pages.append([])

    def text(self, x, y, text, size=10, color=(0, 0, 0), bold=False):
        font = "F2" if bold else "F1"
        r, g, b = [component / 255 for component in color]
        escaped = _escape_pdf_text(text)
        self.pages[-1].append(
            f"BT /{font} {size} Tf {r:.3f} {g:.3f} {b:.3f} rg {x:.2f} {y:.2f} Td ({escaped}) Tj ET"
        )

    def rect(self, x, y, width, height, fill=(255, 255, 255)):
        r, g, b = [component / 255 for component in fill]
        self.pages[-1].append(
            f"{r:.3f} {g:.3f} {b:.3f} rg {x:.2f} {y:.2f} {width:.2f} {height:.2f} re f"
        )

    def render(self):
        objects = [
            b"<< /Type /Catalog /Pages 2 0 R >>",
            None,
            b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
            b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
        ]

        page_refs = []
        for page in self.pages:
            content = "\n".join(page).encode("latin-1", errors="replace")
            content_obj_id = len(objects) + 1
            objects.append(
                b"<< /Length "
                + str(len(content)).encode("ascii")
                + b" >>\nstream\n"
                + content
                + b"\nendstream"
            )
            page_obj_id = len(objects) + 1
            page_refs.append(page_obj_id)
            objects.append(
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_WIDTH} {PAGE_HEIGHT}] "
                f"/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> "
                f"/Contents {content_obj_id} 0 R >>".encode("ascii")
            )

        kids = " ".join(f"{ref} 0 R" for ref in page_refs)
        objects[1] = f"<< /Type /Pages /Kids [{kids}] /Count {len(page_refs)} >>".encode("ascii")

        output = BytesIO()
        output.write(b"%PDF-1.4\n")
        offsets = [0]
        for index, obj in enumerate(objects, start=1):
            offsets.append(output.tell())
            output.write(f"{index} 0 obj\n".encode("ascii"))
            output.write(obj)
            output.write(b"\nendobj\n")

        xref_offset = output.tell()
        output.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
        output.write(b"0000000000 65535 f \n")
        for offset in offsets[1:]:
            output.write(f"{offset:010d} 00000 n \n".encode("ascii"))
        output.write(
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n".encode("ascii")
        )
        return output.getvalue()


def _escape_pdf_text(text):
    text = str(text).encode("latin-1", errors="replace").decode("latin-1")
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
